version: '3.8'

services: 
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - app-networks

  nginx: 
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - app-networks
  
networks:
  app-networks:
    driver: bridge